version: '3.4'

services:
  store-db:
     container_name: postgres_container
     image: postgres
     environment:
        POSTGRES_USER: ${POSTGRES_USER:-phamtuandat1a0}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
     ports:
        - "5432:5432"
     volumes:
        - pgdata:/var/lib/postgresql/data
     networks:
        - postgres
     restart: unless-stopped
   

  gearshop_dotnetapp:
    image: phamtuandat1a0/aspnet:v1.0.1
    build:
      context: .
      dockerfile: gearshop_dotnetapp/Dockerfile
    depends_on:
      - "store-db"
    container_name: app-service
    ports:
      - "4432:4432"
    environment:
      DB_CONNECTION_STRING: "host=store-db;port=5432;database=gearstore-app;username=phamtuandat1a0;password=admin;Pooling=true;"
      CLOUDINARY_URL: "cloudinary://416895123679212:CfXRRhXZEEKah4zLVL5ef49lgbs@dmzvhnnkh"
      ASPNETCORE_ENVIRONMENT: "Production"
    networks:
      - postgres
    
  # frontend:
  #   image: phamtuandat1a0/reactapp
  #   depends_on:
  #    - "store-db"
  #   container_name: react-app
  #   ports:
  #     - 3000:80
  #   networks:
  #    - postgres

volumes:
  pgdata:
networks:
  postgres:
    driver: bridge